import { Component, OnInit, Inject, ComponentFactoryResolver } from '@angular/core';
import { MatDialog, MatDialogRef, MAT_DIALOG_DATA } from '@angular/material/dialog'
import { Data } from '@angular/router';

@Component({
  selector: 'app-entry-view',
  templateUrl: './entry-view.component.html',
  styleUrls: ['./entry-view.component.scss']
})
export class EntryViewComponent implements OnInit {

  fakeEntries = [
    {
      'tags' : ['Parents', 'School', 'College'],
      'name' : 'Second Entry',
      'text' : 'This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever'
    },
    {
      'tags' : ['Friends', 'Family', 'Programming', 'Test'],
      'name' : 'First Entry',
      'text' : '\tThis is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. \n\n\tThis is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever.'
    },
    {
      'tags' : ['Friends', 'Family', 'Programming'],
      'name' : 'First Entry',
      'text' : 'This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever.'
    },
    {
      'tags' : ['Friends', 'Family', 'Programming'],
      'name' : 'First Entry',
      'text' : 'This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever.'
    },
    {
      'tags' : ['Friends', 'Family', 'Programming'],
      'name' : 'First Entry',
      'text' : 'This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever.'
    },
    {
      'tags' : ['Friends', 'Family', 'Programming'],
      'name' : 'First Entry',
      'text' : 'This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever.'
    },
    {
      'tags' : ['Friends', 'Family', 'Programming'],
      'name' : 'First Entry',
      'text' : 'This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever.'
    },
    {
      'tags' : ['Friends', 'Family', 'Programming'],
      'name' : 'First Entry',
      'text' : 'This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever.'
    },
    {
      'tags' : ['Friends', 'Family', 'Programming'],
      'name' : 'First Entry',
      'text' : 'This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever.'
    },
    {
      'tags' : ['Friends', 'Family', 'Programming'],
      'name' : 'First Entry',
      'text' : 'This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever.'
    },
    {
      'tags' : ['Friends', 'Family', 'Programming'],
      'name' : 'First Entry',
      'text' : 'This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever.'
    },
    {
      'tags' : ['Friends', 'Family', 'Programming'],
      'name' : 'First Entry',
      'text' : 'This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever.'
    },
    {
      'tags' : ['Friends', 'Family', 'Programming'],
      'name' : 'First Entry',
      'text' : 'This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever.'
    },
    {
      'tags' : ['Friends', 'Family', 'Programming'],
      'name' : 'First Entry',
      'text' : 'This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever.'
    },
    {
      'tags' : ['Friends', 'Family', 'Programming'],
      'name' : 'First Entry',
      'text' : 'This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever.'
    },
    {
      'tags' : ['Friends', 'Family', 'Programming'],
      'name' : 'First Entry',
      'text' : 'This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever.'
    },
    {
      'tags' : ['Friends', 'Family', 'Programming'],
      'name' : 'First Entry',
      'text' : 'This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever.'
    },
    {
      'tags' : ['Friends', 'Family', 'Programming'],
      'name' : 'First Entry',
      'text' : 'This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever.'
    },
    {
      'tags' : ['Friends', 'Family', 'Programming'],
      'name' : 'First Entry',
      'text' : 'This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever.'
    },
    {
      'tags' : ['Friends', 'Family', 'Programming'],
      'name' : 'First Entry',
      'text' : 'This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever.'
    },
    {
      'tags' : ['Friends', 'Family', 'Programming'],
      'name' : 'First Entry',
      'text' : 'This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever.'
    },
    {
      'tags' : ['Friends', 'Family', 'Programming'],
      'name' : 'First Entry',
      'text' : 'This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever.'
    },
    {
      'tags' : ['Friends', 'Family', 'Programming'],
      'name' : 'First Entry',
      'text' : 'This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever.'
    },
    {
      'tags' : ['Friends', 'Family', 'Programming'],
      'name' : 'First Entry',
      'text' : 'This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever.'
    },
    {
      'tags' : ['Friends', 'Family', 'Programming'],
      'name' : 'First Entry',
      'text' : 'This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever.'
    },
    {
      'tags' : ['Friends', 'Family', 'Programming'],
      'name' : 'First Entry',
      'text' : 'This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever.'
    },
    {
      'tags' : <any>['Friends', 'Family', 'Programming'],
      'name' : 'First Entry',
      'text' : 'This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever. This is a sample entry. It is not very long, but some journal entries can be short. They don\'t all have to ramble about nothing forever.'
    }
  ]
  
  activeEntries = [];
  activeSearchTags = [];
  hidePreview = false;

  constructor(public dialog : MatDialog) { }

  ngOnInit() {
    //Add tags to tagSet
    for(let i = 0; i < this.fakeEntries.length; i++) {
      let entryTags = this.fakeEntries[i].tags;
      this.fakeEntries[i].tags = new Set(entryTags);
    }

    this.filterItems();
  }

  ngAfterViewInit() { }

  openDialog(name, tags, text) {
    const dialogRef = this.dialog.open(EventDialog, {
      height: '80%',
      width: '800px',
      data : {
        name: name,
        tags: tags,
        text: text
      }
    });
  }

  filterItems() {
    this.activeEntries = [];
    //Filter by tag
    let requiredMatches = this.activeSearchTags.length;
    for(let i = 0; i < this.fakeEntries.length; i++) {
      let entry = this.fakeEntries[i];
      let matches = 0;
      for(let j = 0; j < this.activeSearchTags.length; j++) {
        if(!entry.tags.has(this.activeSearchTags[j])) break;
        else matches = matches + 1;
      }
      if(matches == requiredMatches) this.activeEntries.push(entry);
    }

    //TODO: Filter by search terms
  }

  search(elem) {
    //TODO: Place elem as only item in filter bar to search for tag
    //Fires when a tag is clicked on
    console.log(elem);
    for(let i = 0; i < this.activeSearchTags.length; i++) {
      if(this.activeSearchTags[i] == elem) return;
    }

    this.activeSearchTags.push(elem);
    this.filterItems();
  }

  unsearch(elem) {
    for(let i = 0; i < this.activeSearchTags.length; i++) {
      if (this.activeSearchTags[i] == elem) {
        this.activeSearchTags.splice(i, 1);
      }
    }
    this.filterItems();
  }

}

@Component({
  selector: "entry-dialog-",
  templateUrl: "entry-dialog.html",
  styleUrls: ["entry-dialog.scss"]
})
export class EventDialog {
  constructor(
    public dialogRef: MatDialogRef<EventDialog>,
    @Inject(MAT_DIALOG_DATA) public data: Data) { 
      console.log(data);
    }

  onNoClick(): void {
    this.dialogRef.close();
  }

}
